version: "3"

vars:
  PROJECT_ID: moderate-prod
  REGION: europe-west1-b
  CLI_IMAGE_LOCAL_NAME: moderate-cli
  CLI_IMAGE_REMOTE_NAME: agmangas/moderate-cli
  CLI_IMAGE_REMOTE_TAG:
    sh: git rev-parse HEAD | head -c 10

tasks:
  get-credentials:
    desc: Configure kubectl with credentials for the GKE cluster
    cmds:
      - >
        gcloud container clusters get-credentials gke-cluster 
        --region {{.REGION}} 
        --project {{.PROJECT_ID}}

  update-dns:
    desc: Update DNS records to point to the cluster load balancer
    deps:
      - get-credentials
    dir: "{{.ROOT_DIR}}/scripts"
    cmds:
      - ./update-dns.sh

  apply-prod:
    desc: Apply Terraform configuration for the "production" GCP project
    dir: "{{.ROOT_DIR}}/gcp_prod"
    cmds:
      - terraform init
      - terraform apply
      - task: get-credentials
      - task: update-dns

  destroy-prod:
    desc: Destroy Terraform configuration for the "production" GCP project
    dir: "{{.ROOT_DIR}}/gcp_prod"
    cmds:
      - terraform destroy

  push-cli-image:
    desc: Build and push the MODERATE CLI image to the public registry
    cmds:
      - docker buildx build --platform=linux/amd64 -t {{.CLI_IMAGE_LOCAL_NAME}} {{.ROOT_DIR}}/cli
      - docker tag {{.CLI_IMAGE_LOCAL_NAME}} {{.CLI_IMAGE_REMOTE_NAME}}:{{.CLI_IMAGE_REMOTE_TAG}}
      - docker tag {{.CLI_IMAGE_LOCAL_NAME}} {{.CLI_IMAGE_REMOTE_NAME}}:latest
      - docker push {{.CLI_IMAGE_REMOTE_NAME}}:{{.CLI_IMAGE_REMOTE_TAG}}
      - docker push {{.CLI_IMAGE_REMOTE_NAME}}:latest
