# List default UI platform apps. Override via MODERATE_API_PLATFORM_APPLICATIONS_FILE.

brickllm:
  url: https://brick.staging.moderate.cloud/brickllm/
  source_url: https://github.com/EURAC-EEBgroup/BrickLLM-App

building-benchmarking:
  url: https://tools.eeb.eurac.edu/building_benchmarking/
  source_url: https://github.com/MODERATE-Project/MODERATE_building_benchmarking

encome:
  url: https://tools.eeb.eurac.edu/encome/

geo-clustering:
  url: https://tools.eeb.eurac.edu/epc_clustering/piemonte/
  source_url: https://github.com/MODERATE-Project/geoclustering_sensitivity_analysis

solar-cadastre:
  url: https://solar.staging.moderate.cloud/
  source_url: https://github.com/MODERATE-Project/solar-cadastre

lec-assessment:
  url: https://lec.staging.moderate.cloud/
  source_url: https://github.com/MODERATE-Project/lec-location-assessment-tool

epc-quality-check:
  url: http://moderate.five.es:55000/
  source_url: https://github.com/MODERATE-Project/quality-check-report-tool

timeseries-benchmarking:
  url: https://timeseries.staging.moderate.cloud/
  source_url: https://github.com/MODERATE-Project/timeseries-energy-benchmarking
